abstract: OKDaily Web Dictionary Interface
author: Kang-min Liu, C<< <gugod at gugod.org> >>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: WWW-Dict-OKDaily
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Field: 0
  Encode: 0
  WWW::Mechanize: 0
version: 0.01
